apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins-master
  name: jenkins-master
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -v convert
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: jenkins-master
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Djava.awt.headless=true
        image: spikkie/jenkins-server-geneesplaats.nl
        name: jenkins-server-geneesplaats.nl
        ports:
        - containerPort: 8080
        - containerPort: 50000
        resources: {}
        volumeMounts:
        - mountPath: /var/log/jenkins
          name: log
        - mountPath: /var/jenkins_home
          name: data
        - mountPath: /var/run/docker.sock
          name: jenkins-master-claim2
      restartPolicy: Always
      volumes:
      - name: log
        persistentVolumeClaim:
          claimName: log
      - name: data
        persistentVolumeClaim:
          claimName: data
      - name: jenkins-master-claim2
        persistentVolumeClaim:
          claimName: jenkins-master-claim2
status: {}
